//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thalili.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public int user_id { get; set; }
        public int analysis_id { get; set; }
        public int Lab_id { get; set; }
        public Nullable<int> count { get; set; }
    
        public virtual analysis_in_lab analysis_in_lab { get; set; }
        public virtual user user { get; set; }
        public virtual lab lab { get; set; }
    }
}
